spring:
    datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm_1201?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    max-active: 100
    max-idle: 8
    initial-size: 10
    validation-query: select user from dual
    test-while-idle: true
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.lee.spring.cloud.config.client.dao.mapper
